### PR TITLE
Pr09042018

### PR DESCRIPTION
**Pull request by lasdasdas**
Hi @UnaNancyOwen , 

As discussed ages ago, this PR contains a preprocessor macro to enable gps time instead of unix time. Still data packet precision ( no shooting delay LUT for now, but this will eventually be implemented) .  I have also completed the CMakeList.txt of both examples to consider this macro. 

The build is kinda messed up, I had to add a bit more of code to make FindPCAP work in Linux. If you had 
a minute to check that the build still works on Windows it would be great (although I am pretty certain it still does).

### CODE REVIEW

**Comment by UnaNancyOwen** [comment]
Thanks, Looks good to me about code of GPS time.
But, I'm surprised that necessary add this changes (aef0a40) to <code>FindPCAP.cmake</code> for case of Linux.
I hope to keep it simple. Can you make it more simpler?

**Comment by lasdasdas** [comment]
Ok. I'll see what I can do.

**Comment by lasdasdas** [comment]
Check it now, it's much much cleaner. The ${PCAP_LIBRARY_DIR} variable is messing with my builds on linux. I had to put the find_package_handle_standard_arg() so that it only gets sourced if ISFOUND.

**Comment by UnaNancyOwen** [comment]
Good! 👍 
If you want it, I think that it is good to remove <code>PCAP_LIBRARY_DIR</code>. It is not always necessary.

**Comment by lasdasdas** [comment]
Should I remove It then? Is it necessary in any case? I'll commit the changes in a second.

**Comment by lasdasdas** [comment]
Is this what you mean?

**Comment by UnaNancyOwen** [comment]
Yes. On more, Please remove <code>PCAP_LIBRARY_DIR</code> from <code>CMakeLists.txt</code> of samples.

**Comment by lasdasdas** [comment]
I just did it

**Comment by UnaNancyOwen** [comment]
LGTM👍

**Pull request merged**
